/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon Mar  7 13:03:20 2016"
#define BUILD_TIME (1457381000L)

#define VERSION_NUMBER 0x03060002UL
#define VERSION_FEATURES 0x000e0000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.0"
#define VERSION_ID \
 "MacOSX NetHack Version 3.6.0 - last build Mon Mar  7 13:03:20 2016."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0 MacOSX, built Mar  7 13:03:20 2016."

